name: Lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"
          cache: false

      - uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod tidy
      - name: Build Project
        run: go build -v cmd/main.go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
